### ISSUE TITLE
[BUG] Erro mensagem usuário já existe 

### ISSUE THREAD

**Issue by elquercarlos** [reidocoin/4tradex#2]
**Descreva o bug**
Ao tentar cadastrar um e-mail que já existe na base a informação de que o usuario já existe vem em idioma errado, esta vindo em ingles.

**Para reproduzir**
Passos para reproduzir o bug:
1. Acesse https://exchange.4tradex.com/cadastro/novo
2. Preencha com dados de usuario que já exista
3. Clique em acessar
4. Aparecerá abaixo do Cadastre-se

**Comportamento esperado**
Era para estar em PT-BR

**Screenshots**
![image](https://user-images.githubusercontent.com/8761122/92430766-16d45e80-f16c-11ea-93dd-3ff2b8c5d55b.png)

Ocorre em todos navegadores, mobile e desktop

**Comment by brunohass** [comment]
![image](https://user-images.githubusercontent.com/3944338/92868610-46879e80-f3d8-11ea-824d-9654f40a6d76.png)
